# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5baaf01a4e4d4944c621d513d9323d8850a9978d358b1b359f22b9c5e035d76f7dabc397a878f6d4bee5b60af96522022f132e493d5413e07e7b7bf9afd1eddb

test:
  secret_key_base: 5daa748645f0fb8509ec95491ff1223bc0fcdb5e58bacff482e4ff3a4ccb348439f064d7c013a851dbd8cb23fad717d0215f9142ff1614deddfd1d6b41ed421b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
